name: Deploy para AWS ECS

on:
  workflow_run:
    workflows: ["Build e Publicar Docker"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Inicializar Terraform
        run: terraform init
        working-directory: terraform

      - name: Aplicar Terraform (Deploy)
        run: |
          terraform apply -auto-approve \
            -var="dockerhub_username=${{ secrets.DOCKER_USERNAME }}" \
            -var="subnet_id=${{ secrets.SUBNET_ID }}" \
            -var="security_group_id=${{ secrets.SECURITY_GROUP_ID }}"
        working-directory: terraform
