name: Testes E2E com Playwright

on:
  pull_request:
    branches: [main, master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependências
        run: pnpm install

      - name: Instalar navegadores do Playwright
        run: pnpm dlx playwright install

      - name: Rodar testes
        run: pnpm exec playwright test
